const Constants = {
    FILTER_ENABLE:     'FILTER_ENABLE',
    FILTER_DISABLE:    'FILTER_DISABLE',
    FILTER_TOGGLE:     'FILTER_TOGGLE',
    FILTER_REGISTER:   'FILTER_REGISTER',
    FILTER_UNREGISTER: 'FILTER_UNREGISTER',
    FILTER_CLEAR:      'FILTER_CLEAR',
    FILTER_RESET:      'FILTER_RESET'
};

export default Constants;